image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
env:
  azureClientId: 
  azureClientKey: 
  azureTenantId: 
  azureSubscriptionId: 
  aciResourceGroup: 
  aciRegion: 
  nodeName: 
  nodeOsType: 
  apiserverCert: 
  apiserverKey: 
